Fix loss of precision releasegold:withdraw CLI command (#7748)
### Description

This bug fixes the loss of precision (due to converting the `BigNumber` to `number`) in the `releasegold:withdraw` CLI Command.  This was discovered by @zviadm when he tried to use the command to withdraw a contract's full balance.  Due to the loss of precision, the value sent to the contract was higher than the actual balance, leading to the following error:

```
Error: Your request got reverted with the following reason string: Requested amount is greater than available released funds
```

Note that this loss of precision would still constitute a bug even when it doesn't lead to the transaction reverting (since the amount withdrawn is not exactly that requested by the user).

The PR also updates one of the tests for `releasegold:withdraw` to use a more precise assertion which would have caught this bug.

### Tested

Confirmed that the updated test passes, and that before the fix the updated test fails as expected:

```
 FAIL  src/commands/releasegold/withdraw.test.ts (9.881 s)
  releasegold:withdraw cmd
    ✕ can withdraw released gold to beneficiary (3206 ms)
    ✓ can't withdraw the whole balance if there is a cUSD balance (1736 ms)

  ● releasegold:withdraw cmd › can withdraw released gold to beneficiary

    expected 1e+22 to equal 1.0000000000000000000005e+22

      39 |     const balanceAfter = await (await kit.getTotalBalance(beneficiary)).CELO!
      40 |     const difference = balanceAfter.minus(balanceBefore)
    > 41 |     expect(difference).toEqBigNumber(new BigNumber(withdrawalAmount))
         |                        ^
      42 |   })
      43 |
      44 |   test("can't withdraw the whole balance if there is a cUSD balance", async () => {

      at src/commands/releasegold/withdraw.test.ts:41:24
      at fulfilled (src/commands/releasegold/withdraw.test.ts:5:58)
```

### Backwards compatibility

No change in the interface, the PR simply makes the command's behavior match the expected behavior (withdrawing the exact amount specified)