Allow yarn install and yarn build with node 14
The v8 engine's method of Object
  "bool Set(Local<Value> key, Local<Value> value)"
was deprecated in the verison of v8 used in node 12
and removed in node 14.

This was resulting in in errors of the form:

  error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>&)’

when trying to build sha3 or usb with node 14, the fix was to update the
packages with resolutions.