Check RPC after geth startup to reduce flakiness
This is meant to avoid the following errors that happens across most
(all?) e2e tests from time to time:
```
 Error: Connection refused or URL couldn't be resolved: http://localhost:8545
  at XMLHttpRequest.request.onreadystatechange (/home/circleci/app/node_modules/web3-providers/dist/web3-providers.cjs.js:759:22)
  at XMLHttpRequestEventTarget.dispatchEvent (/home/circleci/app/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
  at XMLHttpRequest._setReadyState (/home/circleci/app/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
  at XMLHttpRequest._onHttpRequestError (/home/circleci/app/node_modules/xhr2-cookies/xml-http-request.ts:379:8)
  at ClientRequest.<anonymous> (/home/circleci/app/node_modules/xhr2-cookies/xml-http-request.ts:266:37)
  at Socket.socketErrorListener (_http_client.js:406:9)
  at emitErrorNT (internal/streams/destroy.js:92:8)
  at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
  at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I am not sure this actually works as intended, but I could not reproduce
the problem after this change, anymore. So it is worth testing it out,
as we can easily revert the change or improve the approach.